# Generated by Django 4.0.6 on 2022-07-14 20:39

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
