# Generated by Django 4.0.6 on 2022-07-14 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 14, 8, 58, 410931)),
        ),
    ]
