# Generated by Django 4.0.6 on 2022-07-14 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_url_clicks_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 21, 12, 2, 582357)),
        ),
    ]
